### ISSUE TITLE
Error from LibGTK3-noCSD

### ISSUE THREAD

**Issue by lproven** [taviso/wpunix#1]
I am getting an error I do not know how to parse:

````
$  wp
/opt/wp70/wpbin/wp: error in loading shared libraries
/usr/lib/x86_64-linux-gnu/libgtk3-nocsd.so.0: ELF file class not __ELF_WORDSIZE-bit
````

This is on Ubuntu 22.04, fully updated.

**Comment by taviso** [comment]
Hmm, that's confusing - It seems to work on 22.04 here.

Is it possible you have something in `/etc/ld.so.preload` or `$LD_PRELOAD`?

**Comment by lproven** [comment]
It does seem to have been a setting in `$LD_PRELOAD`! 

The odd thing is that I only had anything in there at all because I was flailing around after installing it and the initial failure to start. I am both mystified, and very sorry for the noise.

I don't know if you saw that I wrote a story on the Register about your 1-2-3 r3 port. I think there may well be a follow up on this one! :-) I will drop you an email. Thank you -- this is amazing work!
