### ISSUE TITLE
Some filtrix converters are broken

### ISSUE THREAD

**Issue by taviso** [taviso/wpunix#12]
Some filtrix converters do not appear to be working correctly.

Investigate what's breaking.

Reproduce:

Ctrl+F5,Save As, Choose MS Word 6. The operation will fail.

**Comment by emendelson** [comment]
I don't know if this is relevant, but I *think* the ones that are broken are the ones that are NOT listed when you run /opt/wp80/shbin10/cvt and see a list of output formats.

**Comment by taviso** [comment]
I think the problem is that all these converters were not written by Corel, they were written by "Blueberry Software" and Corel only distributed them with a license. So they're checking if the distribution "expiry" date has expired, and it doesn't work correctly because the date was so long ago.

I have a patch that just removes that check, I guess that's good enough.
