### ISSUE TITLE
setarch causes issue

### ISSUE THREAD

**Issue by Vasja1986** [taviso/wpunix#14]
Regarding the following commit: https://github.com/taviso/wpunix/commit/3a693fe7558fb3c55f4350ec59af23e7ee9114af

When I try to launch wp from a terminal I get the following error:
`setarch: no architecture argument specified`

Subsequently wp does not start.

When creating a copy of /usr/bin/wp that omits the setarch statement wp does start, just like it did previously before the aforementioned commit.

**Comment by taviso** [comment]
Oops -- sorry about that, recent versions make the arch optional.

I added it back.

**Comment by taviso** [comment]
I'm working on a patch to make the preview screen scale to the terminal size #13, as soon as that's finished I'll make a new release with this fix!
