### ISSUE TITLE
Tiny suggestion for README.md

### ISSUE THREAD

**Issue by DJGoossens** [taviso/wpunix#16]
I suggest adding rpm2cpio to your list of dependencies.

It's just an idea, but a project like this is likely to be attractive to people who do not always 'get under the bonnet' on their computer -- that is, people who are interested in WordPerfect but maybe not in computers as such. You might consider pitching the instructions at a lower level than you typically would do. For example:

1. Clone the archive or download and unzip the file at https://github.com/taviso/wpunix/archive/refs/heads/main.zip.
2. cd into the new directory.
3. Move the downloaded ISO file into the directory.
4. Install dependencies, then build and install WordPerfect; for example on Debian:
    $ sudo apt install build-essential gcc-multilib bsdtar patchelf rpm2cpio
5. $ make
6. $ sudo dpkg -i wordperfect8_i386.deb

Anyway, thanks for a great project. I love some of the old word processors, and I like not needing X. Between this project and your Lotus project, you'll have a Linux productivity platform that can run in just a few MB of RAM...!

**Comment by taviso** [comment]
Oops, you're right about rpm2cpio - I'll add that, thanks!

Yeah, I'm not really the best at documentation! 😄 

I'm trying to flesh out the wiki as I go with instructions, but the README definitely needs better build instructions. I'll try to work on this over the weekend.
