### ISSUE TITLE
Temporary macros not working

### ISSUE THREAD

**Issue by taviso** [taviso/wpunix#20]
I think if you hit enter on the `Macro: ` prompt when you press <kbd>Alt</kbd>-<kbd>F10</kbd>, it's supposed to record a temporary macro... but that doesn't seem to work.

Investigate what is going wrong.

**Comment by emendelson** [comment]
Away from my machine and can't check but I think it's Ctrl-F10 that records the macro; Alt-F10 plays it back.

**Comment by taviso** [comment]
Oops, yes - seems like user error! It should give a better error though, maybe I should patch that.

**Comment by emendelson** [comment]
The DOS version doesn't give an error message. But, as you say, maybe it would be good to give something like:

"No temporary macro has been recorded."

Just a thought: you'll come up with better wording.
