### ISSUE TITLE
Indent

### ISSUE THREAD

**Issue by abenson** [taviso/wpunix#26]
Trouble with `[Indent->]`, it should be `F4`.  `Shift-F4` properly inserts `[->Indent<-]`, but in the keyboard settings I can't even enter `F4` to bind it to anything.  Tried with a few different VTE based terminals (mate, gnome) and xterm; I know `F4` works and sends correctly to other programs.  Am I missing something?

**Comment by taviso** [comment]
Oops - you're right, there's a typo! I've committed a fix, I'll probably make a new release in a few days.
