### ISSUE TITLE
Ghostscript and alternate page sizes

### ISSUE THREAD

**Issue by abenson** [taviso/wpunix#30]
I've noticed that the margins, particularly the top and bottom especially when modified, do not behave correctly if the page size is modified to something other than Letter (namely A4).

I'll need to properly sort it all out, but the same file when printed with, for example, the Apple LaserWriter, generates proper margin placement in the resulting postscript.

**Comment by emendelson** [comment]
I believe the only difference in the way the Ghostscript driver and the LaserWriter IINTX driver format pages is that the Ghostscript driver sets the minimum page margins to zero, while the driver for the LaserWriter sets the minimum margins to 0.3 inches (which is the actual minimum for the physical printer). Is it possible that you're seeing a 0.3" difference between the two outputs?

**Comment by abenson** [comment]
I need to do some more testing, I'm having trouble recreating the issue right now, and I think it may have actually been an issue when I physically printed something (i.e. paper type mismatch, document/PDF are A4, printer is loaded with A4, but PDF viewer was set to print to letter).
