### ISSUE TITLE
The DOS ptr.exe utility wrapped as a 32-bit app that runs under Wine (not an issue!) 

### ISSUE THREAD

**Issue by emendelson** [taviso/wpunix#32]
Because there seems to be no native Unix equivalent of the ptr.exe program that edits WP printer drivers, I've put together a 32-bit Windows executable that wraps ptr.exe so that it can  under Wine on the Mac, and presumably also under Wine in Linux (though I haven't tested it). It can be downloaded here:

https://www.dropbox.com/s/iknsur9f4oix586/5ptr32.7z?dl=0

The program that wraps the DOS app for 32-bit windows is here:

http://takeda-toshiya.my.coocan.jp/msdos/index.html 

There are two versions of the wrapped ptr32.exe executable in the 7z file; the one named Ptr32.exe pretends to be a DOS program (though I don't know what that means); the one named Ptr32Win.exe identifies itself as a Windows program. At least, that's what the msdos.exe help file says.

On the Mac, I use the Wine configuration utility to map macOS directories to Windows drive letters, and presumably this could be done under Linux also.

I realize that ptr.exe runs under dosemu2, but perhaps this makes it easier to use. 

-

**Comment by taviso** [comment]
I think a better solution is to write a new program that can generate PRS files from a text description we can keep in revision control and track changes, but that's a big project and it's not really urgent as I think we have good ghostscript support!
