### ISSUE TITLE
probably basic build error : error in loading shared libraries

### ISSUE THREAD

**Issue by prepstarr** [taviso/wpunix#35]
paul@paul-Lenovo-Yoga-2-11:~$ wp
/opt/wp80/wpbin/wp: error in loading shared libraries
/opt/wp80/lib/libwppatch.so: undefined symbol: __memcpy_chk
paul@paul-Lenovo-Yoga-2-11:~$

**Comment by taviso** [comment]
Hmm interesting, it's compiled with `-fno-stack-protector`. Did you build this yourself? Which Distro/version?

**Comment by prepstarr** [comment]
yes built myself from this repository

**Comment by taviso** [comment]
Sorry about that! Which distro? I'll figure out what happened and fix it.

**Comment by prepstarr** [comment]
wp8.0 I believe

**Comment by prepstarr** [comment]
that was annoying must have hit the wrong button issue is still open

**Comment by taviso** [comment]
I mean Linux Distribution, Like Debian, Ubuntu, Fedora?

**Comment by prepstarr** [comment]
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by prepstarr** [comment]
paul@paul-Lenovo-Yoga-2-11:~/Documents/wpunix$ sudo apt --reinstall install ./wordperfect8_i386.deb
[sudo] Mot de passe de paul : 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Note : sélection de « wordperfect:i386 » au lieu de « ./wordperfect8_i386.deb »
0 mis à jour, 0 nouvellement installés, 1 réinstallés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 0 o/14,8 Mo dans les archives.
Après cette opération, 0 o d'espace disque supplémentaires seront utilisés.
Réception de :1 /home/paul/Documents/wpunix/wordperfect8_i386.deb wordperfect i386 8.0 [14,8 MB]
(Lecture de la base de données... 202499 fichiers et répertoires déjà installés.
)
Préparation du dépaquetage de .../wpunix/wordperfect8_i386.deb ...
Dépaquetage de wordperfect:i386 (8.0) sur (8.0) ...
Paramétrage de wordperfect:i386 (8.0) ...
N: Le téléchargement est effectué en dehors du bac à sable en tant que « root » car le fichier « /home/paul/Documents/wpunix/wordperfect8_i386.deb » n'est pas accessible par l'utilisateur « _apt ». - pkgAcquire::Run (13: Permission non accordée)
paul@paul-Lenovo-Yoga-2-11:~/Documents/wpunix$ wp
/opt/wp80/wpbin/wp: error in loading shared libraries
/opt/wp80/lib/libwppatch.so: undefined symbol: __memcpy_chk
paul@paul-Lenovo-Yoga-2-11:~/Documents/wpunix$

**Comment by taviso** [comment]
I see - apparently Ubuntu have started defining fortify source by default.

No problem, patch on the way!

**Comment by taviso** [comment]
Please `git pull`, then `make clean` and try again - I think it should work now!

**Comment by prepstarr** [comment]
I have the following files to perhaps help
[make.txt](https://github.com/taviso/wpunix/files/10312326/make.txt)
[clean.txt](https://github.com/taviso/wpunix/files/10312327/clean.txt)

**Comment by prepstarr** [comment]
not this is without the git pull , doing it again with git pull...

**Comment by prepstarr** [comment]
[make.txt](https://github.com/taviso/wpunix/files/10312337/make.txt)

**Comment by prepstarr** [comment]
![image](https://user-images.githubusercontent.com/65930206/209763754-68de7e06-33e8-469a-8113-0a1cdcc62b67.png)

**Comment by taviso** [comment]
Thanks for verifying! 👍
