### ISSUE TITLE
Backspace Issues

### ISSUE THREAD

**Issue by abenson** [taviso/wpunix#41]
It's probably a terminal setting, but I haven't figured out which one.  On some terminals, namely xterm under linux and the FreeBSD console (ssh'd in to my linux system right now), backspace will delete the entire word, but not delete anything if there's a space.  Holding Control down while hitting backspace will delete characters.  Any ideas on which setting to change?  I've tried a few things with `stty` but no luck.

**Comment by taviso** [comment]
Hmm - the default has `^H`  as `Delete Word` and DEL (i.e. `^?`) as `Backspace`.

If you do `stty -a` what is erase? I'm guessing it's `^H`?

**Comment by taviso** [comment]
BTW, if you just want to get it working, I think you can toggle `Backarrow Key` in the XTerm menu (<kbd>Ctrl</kbd>+Left Click)!
