### ISSUE TITLE
README fix:

### ISSUE THREAD

**Issue by GravisZro** [taviso/wpunix#44]
As interesting as this is, you have completely omitted which version of WordPerfect for UNIX this applies to which should really be in the first line of the README file.  Assuming it's WP8 then I would suggest:

> This is a set of build scripts and patches to make WordPerfect for UNIX (8.x) work on modern Linux.

I would also suggest a link to [where it can be had](https://winworldpc.com/product/wordperfect/8x-unix) but that's your call.

**Comment by emendelson** [comment]
The page already has a link to the same CD image that's on winworldpc.com. See the sentence that read:

`You need the following file to build this, available [here](https://archive.org/details/corel-wpunix-8/box_f.jpg).`

**Comment by dialognewmedia-mws** [comment]
Since #45 addresses this issue, I believe this could be closed, right?

**Comment by taviso** [comment]
Thank you!
