### ISSUE TITLE
16 bit or 32 bit ? WP version?

### ISSUE THREAD

**Issue by toncho11** [taviso/wpunix#55]
Hi,

Which version of word perfect is that?

It was a 16 bit or 32 bit Unix? Maybe it can be ported to other Unix / Linux?

**Comment by taviso** [comment]
32bit, it will probably work on BSD with Linux emulation... in theory it could be ported to arm or x86-64, but that is a *lot* of work and we would need a lot of volunteers to help!

**Comment by toncho11** [comment]
Please add to the readme that it is 32 bit. So this version uses precomputed binaries, so there is no chance of porting it to 16 bit Linux like OS, right?

**Comment by abenson** [comment]
What 16-bit Linux-like are you hoping to target?

**Comment by taviso** [comment]
Yeah, I can't imagine what OS you're talking about...!

WordPerfect was available for several 16bit systems, like MS-DOS and Apple II for example... It is also available for several 32-bit UNIX variants (Solaris/Sparc, Xenix/x86, AIX (probably power?), HP-UX/PA-RISC), but the version maintained here is Linux specific, and I'm not familiar enough with those other systems to maintain those ports!

**Comment by toncho11** [comment]
It is https://github.com/ghaerr/elks

Its applications are compiled with a 16 bit gcc mainly and recently a 16 bit open watcom can be used as well.

**Comment by taviso** [comment]
cool! Yes, it's not possible - if you have any way of running DOS software (like dosemu), then you could run the DOS version.

**Comment by johnsonjh** [comment]
It *might* be possible to port something like https://github.com/dmsc/emu2 to ELKS.  I know WordPerfect 5.1 works on a plain 8088 - not sure about WP6 or later though.

**Comment by dialognewmedia-mws** [comment]
WordPerfect DOS 6.x requires a 286 or higher

**Comment by dialognewmedia-mws** [comment]
This issue seems like it could be closed

**Comment by toncho11** [comment]
Thanks.

**Comment by abenson** [comment]
> I know WordPerfect 5.1 works on a plain 8088

Yeah, I run 5.1+ (with the screen extender) on my 8088/NEC V20.
