### ISSUE TITLE
Page 2 Typing flow?

### ISSUE THREAD

**Issue by krionical** [taviso/wpunix#59]
Opensuse distro: When typing and the overflow on the screen goes to the next page, weird things start happening like character substitution and the next page not starting.

**Comment by abenson** [comment]
Can you describe your setup (distro version, terminal, etc) as well as provide screenshots demonstrating what you're describing?

**Comment by krionical** [comment]
I spent around four or five hours yesterday on the issue, and decided to
move on and uninstalled it. Word perfect is a great program, but it's
possible it just isn't cut out for this time on a linux machine. For people
that have time to tinker with it though, maybe eventually the gap will be
closed.

I used the rpm build, and the distro was tumbleweed. Xfce was the terminal.
At the bottom of the screen it would not automatically move to the next
page, but instead crunched up all the sentences in an odd way and
recombined them with the above sentences. I am providing this info more for
future reference as I intend to close the issue as it is "fixed for me" in
the sense that I uninstalled it.

**Comment by emendelson** [comment]
Strange. Doesn't happen in WSL or Ubuntu.

**Comment by krionical** [comment]
No. Most things run in Ubuntu and Debian. Broad use cases.Sent from my iPhoneOn Sep 2, 2024, at 12:30 PM, emendelson ***@***.***> wrote:﻿
Strange. Doesn't happen in WSL or Ubuntu.

**Comment by abenson** [comment]
I can't recreate it in Void Linux using the same RPM.

**Comment by krionical** [comment]
Brief update: Worked on an arch distro and a debian based distro. I think the problem was somewhere between nvidia and opensuse.
