### ISSUE TITLE
Control Enter does not generate a Hard Page Break

### ISSUE THREAD

**Issue by Vasja1986** [taviso/wpunix#6]
If you are pressing Control-Enter a Hard Page Break should be inserted according to the online documentation. Instead a regular Hrt is inserted.

**Comment by taviso** [comment]
Ah, you're right. I think ctrl-enter is not reliable across terminals, I think we could use alt-enter instead?

**Comment by taviso** [comment]
<kbd>Alt</kbd>+<kbd>Enter</kbd> is no problem on Linux, but on Windows that key is reserved.

I guess it's the same thing as <kbd>Esc</kbd>,<kbd>Enter</kbd> though, so they can just use that.
